name: Deploy to GitHub Pages

on:
    push:
        branches:
            - build

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Set up Node
              uses: actions/setup-node@v2

            - run: yarn install
            - run: yarn build

            - name: Deploy
              uses: crazy-max/ghaction-github-pages@v2
              with:
                  target_branch: gh-pages
                  build_dir: target
                  fqdn: hydrogen.alefvanoon.xyz
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - uses: aquiladev/ipfs-action@master
              id: ipfs-add
              with:
                path: ./public
                service: infura
                verbose: true
                timeout: 180000
            - name: Update DNSLink
              run: npx dnslink-cloudflare -d alefvanoon.xyz -l /ipfs/${{ steps.ipfs-add.outputs.hash }} -r _dnslink.hydrogen
              env:
                CF_API_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
